### ISSUE TITLE
package-lock.json points to SAS npm registry

### ISSUE THREAD

**Issue by danchildsas** [sassoftware/vi-solution-extensions#1]
Hello,

I noticed that the package-lock.json points to the SAS npm registry. Non-SAS users of this repository will experience errors when running `npm install`

Dan

**Comment by daniel-arthur-sas** [comment]
@danchildsas Thank you for reporting this issue. This should now be resolved by commit a17b598eb5ebe97b2971c5ee6698a5fadace6f63 as the linked attachments example  `package-lock` now points to the public NPM registry.
