### ISSUE TITLE
@sassoftware/vi-api depnds on @sas/nexus-shared-ui

### ISSUE THREAD

**Issue by danchildsas** [sassoftware/vi-solution-extensions#2]
Hello,

When running `npm run watch` an error is thrown. The package @sassoftware/vi-api depends on @sas/nexus-shared-ui which isn't available to the public. Because of this, only internal SAS employees can develop solution extensions, or @sas/nexus-shared-ui must be downloaded just to run `npm run watch`.

Dan

**Comment by daniel-arthur-sas** [comment]
@danchildsas Thank you for reporting this issue. This should now be fixed in the latest version of the [@sassoftware/vi-api](https://www.npmjs.com/package/@sassoftware/vi-api) package
