### ISSUE TITLE
@sas/nexus-shared-ui  in package.json

### ISSUE THREAD

**Issue by danchildsas** [sassoftware/vi-solution-extensions#3]
Hello,

The @sas/nexus-shared-ui library is listed in the package.json. This should not be a default as public users do not have access to @sas/nexus-shared-ui but should instead be using the kendo components.

Dan

**Comment by KuzcoCharp** [comment]
Adding to this: As an external user, when I build a solution extension using this guide, @sas/nexus-shared-ui/identities/input is listed as an import in metadata-api.d.ts, causing builds to fail. I have to go in and remove that import and then  the line
`authorizedToRevealMasked?: IIdentityOption[];` at line 83.

Can we get a fix for this please?

**Comment by daniel-arthur-sas** [comment]
Thank you for reporting these issues.

@danchildsas The library `@sas/nexus-shared-ui` should now be omitted from the linked attachments example dependencies as of commit a17b598eb5ebe97b2971c5ee6698a5fadace6f63. 

 @KuzcoCharp This issue should be fixed as of version [v1.15.2](https://www.npmjs.com/package/@sassoftware/vi-api/v/1.15.2) of `@sassoftware/vi-api` (currently [v1.40.4](https://www.npmjs.com/package/@sassoftware/vi-api/v/1.40.4?activeTab=code) is the latest release).
